version: '3.1'

services:

  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ubu

  mariadb:
    image: mariadb:10.9.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ubu

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ubu

  couchdb:
    image: couchdb:3.2.2
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: ubu
