# Generated by Django 4.1.3 on 2023-03-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BookfoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BootData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CookData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CookingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EqipanoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FirstaidData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Forest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="ชื่อ")),
                ("image", models.TextField(verbose_name="รูป")),
                ("Level", models.TextField(verbose_name="ความยาก")),
                ("Season", models.TextField(verbose_name="เดือน/ฤดูกาล")),
                ("Stop", models.TextField(verbose_name="ปิดฟื้นฟูธรรมชาติ")),
                ("Distance", models.TextField(verbose_name="ระยะทาง")),
                ("Time", models.TextField(verbose_name="เวลา")),
                ("Details", models.TextField(verbose_name="รายละเอียด")),
            ],
        ),
        migrations.CreateModel(
            name="JacketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="KnifeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LEDData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MapData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PortalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SLData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SleepData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ToiletData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ZipoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField()),
                ("date", models.TextField()),
                ("details", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
