# Generated by Django 4.1.3 on 2022-11-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.FloatField(default=12, verbose_name="กว้าง")),
                ("heigth", models.FloatField(default=20, verbose_name="ยาว")),
                ("tall", models.FloatField(default=200, verbose_name="สูง")),
            ],
        ),
    ]
