# Generated by Django 4.1.3 on 2022-12-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eqipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.TextField(verbose_name="หมวดหมู่")),
                ("Type", models.TextField(verbose_name="ประเภท")),
                ("Price", models.TextField(verbose_name="ราคา")),
            ],
        ),
        migrations.CreateModel(
            name="Forest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="ชื่อ")),
                (
                    "image",
                    models.ImageField(upload_to="imageForest", verbose_name="รูป"),
                ),
                ("Level", models.TextField(verbose_name="ความยาก")),
                ("Season", models.TextField(verbose_name="เดือน/ฤดูกาล")),
                ("Distance", models.TextField(verbose_name="ระยะทาง")),
                ("Time", models.TextField(verbose_name="เวลา")),
            ],
        ),
        migrations.DeleteModel(
            name="Sao",
        ),
    ]
