# Generated by Django 4.1.3 on 2022-12-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_eqipment_forest_delete_sao"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Eqipment",
        ),
    ]
